import type { ResumeData } from '@/types/resume'

export const DEMO_RESUME: ResumeData = {
  personalInfo: {
    fullName: 'Alex Chen',
    title: 'Senior Software Engineer',
    email: 'alex.chen@email.com',
    phone: '+1 (415) 555-0192',
    location: 'San Francisco, CA',
    linkedIn: 'linkedin.com/in/alexchen',
    github: 'github.com/alexchen',
    portfolio: 'alexchen.dev',
    summary: 'Senior Software Engineer with 6+ years of experience building scalable distributed systems and high-performance web applications. Led teams of 5–8 engineers at Series B startups and Fortune 500 companies. Passionate about developer experience, system reliability, and mentoring junior engineers.',
  },
  experience: [
    {
      id: '1',
      title: 'Senior Software Engineer',
      company: 'TechCorp Inc.',
      location: 'San Francisco, CA',
      startDate: '2022-03',
      endDate: '',
      current: true,
      bullets: [
        'Architected a real-time event processing pipeline handling 2M+ events/day using Kafka and Go, reducing latency by 65%',
        'Led migration of monolithic Rails app to microservices, cutting deployment time from 45 minutes to 8 minutes',
        'Mentored 4 junior engineers through weekly 1:1s and code reviews, with 2 promoted to mid-level within 12 months',
        'Reduced AWS infrastructure costs by $180K/year by optimizing EC2 instance types and implementing auto-scaling',
      ],
      technologies: ['Go', 'Kafka', 'AWS', 'Docker', 'Kubernetes', 'PostgreSQL'],
    },
    {
      id: '2',
      title: 'Software Engineer II',
      company: 'StartupXYZ',
      location: 'New York, NY',
      startDate: '2019-06',
      endDate: '2022-02',
      current: false,
      bullets: [
        'Built REST API serving 50K daily active users using Node.js and TypeScript, achieving 99.9% uptime SLA',
        'Implemented OAuth 2.0 authentication system that reduced login friction by 40%, increasing conversion by 12%',
        'Designed and shipped a real-time dashboard using React and WebSockets, used by 200+ enterprise customers',
      ],
      technologies: ['Node.js', 'TypeScript', 'React', 'PostgreSQL', 'Redis', 'AWS'],
    },
  ],
  projects: [
    {
      id: '1',
      name: 'OpenSearch Accelerator',
      description: 'Open-source query optimization library for Elasticsearch',
      bullets: [
        'Developed query caching layer that improved p99 search latency from 450ms to 85ms',
        'Gained 1.2K GitHub stars and 30+ contributors within 3 months of launch',
      ],
      technologies: ['Go', 'Elasticsearch', 'Redis'],
      repoUrl: 'github.com/alexchen/opensearch-accelerator',
      liveUrl: '',
      startDate: '2023-01',
      endDate: '2023-06',
    },
  ],
  skills: [
    { id: '1', name: 'Go', level: 'expert', category: 'Languages' },
    { id: '2', name: 'TypeScript', level: 'expert', category: 'Languages' },
    { id: '3', name: 'Python', level: 'advanced', category: 'Languages' },
    { id: '4', name: 'React', level: 'advanced', category: 'Frameworks' },
    { id: '5', name: 'Node.js', level: 'advanced', category: 'Frameworks' },
    { id: '6', name: 'Kubernetes', level: 'advanced', category: 'Infrastructure' },
    { id: '7', name: 'AWS', level: 'advanced', category: 'Infrastructure' },
    { id: '8', name: 'PostgreSQL', level: 'expert', category: 'Databases' },
    { id: '9', name: 'Redis', level: 'advanced', category: 'Databases' },
    { id: '10', name: 'Kafka', level: 'intermediate', category: 'Infrastructure' },
  ],
  education: [
    {
      id: '1',
      institution: 'UC Berkeley',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      location: 'Berkeley, CA',
      startDate: '2015-08',
      endDate: '2019-05',
      gpa: '3.8',
      honors: 'Magna Cum Laude',
      coursework: ['Distributed Systems', 'Algorithms', 'Machine Learning', 'Operating Systems'],
    },
  ],
  certifications: [
    {
      id: '1',
      name: 'AWS Solutions Architect Professional',
      issuer: 'Amazon Web Services',
      issueDate: '2023-03',
      expiryDate: '2026-03',
      credentialId: 'AWS-SAP-12345',
      url: 'aws.amazon.com/certification',
    },
  ],
}
